# build configuration file
targets:
  menu:
    valid_arch: all
    base_dir: bootmenu
    sources:
      - osldr
      - atop
      - menu
      - libstd
  boot:
    valid_arch: x64 i386
    base_dir: boot
    sources:
      - boot
      - bootpg
      - peldr
      - bootasm.asm
  kernel.bin:
    valid_arch: x64
    base_dir: kernel
    no_suffix: true
    subsystem: native
    cflags: -mno-sse
    sources:
      - acpi
      - arch
      - asmpart.asm
      - gs
      - hidmgr
      - kernel
      - libstd
      - lpc
      - memory
      - moe
      - page
      - shell
      - usb
      - xhci
      - cpuid
